[package]
name = "testing"
version = "0.1.0"
authors = ["John Kåre Alsaker <john.kare.alsaker@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
smallvec = { path = ".." }

[profile.release]
debug = true